# NOTE: Currently disabled. Due to symlinking errors (`link already exists`)
# when building Cython during Pynini compilation.

name: "macos"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test-macos:
    name: Build and Test (macOS)
    runs-on: macos-latest
    env:
      BAZEL: bazelisk-darwin-amd64
      CC: gcc
      CXX: g++

    steps:
    - uses: actions/checkout@v3

    - name: Update environment variables
      run: |
        echo "USER=${USER}" >> ${GITHUB_ENV}

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        # See https://docs.bazel.build/versions/master/output_directories.html
        path: /private/var/tmp/_bazel_${{ env.USER }}
        key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE.bazel') }}
        restore-keys: ${{ runner.os }}-bazel

    - name: Install bazelisk
      run: |
        curl -sLO "https://github.com/bazelbuild/bazelisk/releases/latest/download/$BAZEL"
        chmod +x $BAZEL

    - name: Install requirements
      run: |
        brew install --display-times python || true
        pip3 install -r ./requirements.txt

    - name: Environment variables (debug dump)
      run: |
        echo "====== gcc version:"
        gcc --version
        echo "====== Requested gcc:"
        ${CC} --version
        echo "====== g++ version:"
        g++ --version
        echo "====== Requested g++:"
        ${CXX} --version

    - name: Build
      run: ./$BAZEL build -c opt //...

    - name: Test
      run: ./$BAZEL test -c opt --test_size_filters=-large,-enormous --test_output=errors //...
